# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set outputs
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Repository Name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.repo-name.outputs.repository-name }}-${{ steps.short_sha.outputs.sha_short }}
          path: target/*.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.repo-name.outputs.repository-name }}
          tag_name: ${{ steps.short_sha.outputs.sha_short }}
          body: |
            This release is automatically compiled by GitHub Actions
          files: |
            target/*.jar
          generate_release_notes: true
