name: Build and Release

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "1 0 * * *"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set outputs
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Repository Name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.repo-name.outputs.repository-name }}-${{ steps.short_sha.outputs.sha_short }}
          path: target/*.jar

      - name: Publish to GitHub Packages
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.repo-name.outputs.repository-name }}
          tag_name: ${{ steps.short_sha.outputs.sha_short }}
          body: |
            This release is automatically compiled by GitHub Actions
          files: |
            target/*.jar
          generate_release_notes: true
